### ISSUE TITLE
`npm run dev` cause an error

### ISSUE THREAD

**Issue by pengfu** [xufei/vue-rx-demo#1]
As described in title, an error occurs when `npm run dev`
E:\github\vue-rx-demo-master>npm run dev

> vue-rx-demo@ dev E:\github\vue-rx-demo-master
> cross-env NODE_ENV=development webpack-dev-server --open --inline --hot

E:\github\vue-rx-demo-master\node_modules\debug\debug.js:126
  debug.color = selectColor(namespae);
                            ^

ReferenceError: namespae is not defined
    at createDebug (E:\github\vue-rx-demo-master\node_modules\debug\debug.js:126:29)
    at Object.<anonymous> (E:\github\vue-rx-demo-master\node_modules\portfinder\lib\portfinder.js:18:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\github\vue-rx-demo-master\node_modules\webpack-dev-server\bin\webpack-dev-server.js:8:18)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! vue-rx-demo@ dev: `cross-env NODE_ENV=development webpack-dev-server --open --inline --hot`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-rx-demo@ dev script 'cross-env NODE_ENV=development webpack-dev-server --open --inline --hot'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-rx-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development webpack-dev-server --open --inline --hot
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-rx-demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-rx-demo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\github\vue-rx-demo-master\npm-debug.log

**Comment by pengfu** [comment]
My node version is v6.9.1
